### ISSUE TITLE
No function for controlling sound sensitivity 

### ISSUE THREAD

**Issue by ch-muhammad-adil** [cmusphinx/pocketsphinx-android-demo#16]
Hello !

Demo works great and this library is really helpful. I found no function for setting sensitivity of mic to hear a sound in **SpeechRecognizer.java **. Is it possible that you add a function for sound sensitivity to give better user experience. 
Thanks!

**Comment by nshmyrev** [comment]
Pocketsphinx automatically adjusts recording volume in process of recognition, there is no such thing as "sensitivity" then. If you meet some specific problems with recognition you need to describe them in more details. You need to provide corresponding audio recordings in order to reproduce your problems.

**Comment by chrisspen** [comment]
Is there any way to get PocketSphinx to work on lower volumes? Even with the mic placed very close to your mouth, it only seems to work if you speak fairly loudly. I'd like to get it to work by just whispering, which it doesn't currently seem to work with.

**Comment by nshmyrev** [comment]
Whisper speech recognition is not supported and requires significant work.
