### ISSUE TITLE
Not Compiling on Android Studio 1.5

### ISSUE THREAD

**Issue by WorlazMighty** [cmusphinx/pocketsphinx-android-demo#9]
Am having a very tough time using these package. The requirements are add Ndk path. I've done that. add Ask version. I've done that. make the gradle.build access the assets.xml I've done that and yet still am getting this error.

       Plugin with Id android.application not found.

What should I do. Its being 3 days now. Is the package outdated. Any Solutions.

**Comment by nshmyrev** [comment]
Please read this:

http://stackoverflow.com/questions/24795079/error1-0-plugin-with-id-com-android-application-not-found

In case of trouble learn to report errors precisely, that will save your development time.

Also learn to share as much information as possible in order to get help. You need to share versions of the software you are using, the project files you created and so on. The more information you share the faster you get an answer.
